### ISSUE TITLE
To-Do List (Deadline: 13/04)

### ISSUE THREAD

**Issue by gabriel-vieira06** [gabriel-vieira06/ProjetoSO01-2022.01#1]
# Lista de Afazeres

### Threads

- [x] Empacotador bloqueado quando Caixas == M?
- [x] Trem bloqueado em A quando Caixas < N?
- [x] Trem *NÃO* pode ser instanciado múltiplas vezes?
- [x] Empacotador pode ser instanciado múltiplas vezes?

### Main

- [x] Chamada ás Threads ocorre sem problemas?

### Interface Gráfica

- [x] Trem aparece indo de A à B?
- [x] Trem aparece voltando de B para A?
- [x] Empacotador aparece empacotando a caixa?
- [x] Múltiplos empacotadores aparecem trabalhando?
- [x] O Trem para quando bloqueado?
- [x] O Empacotador para quando bloqueado?
- [x] Podemos instanciar múltiplos Empacotadores?
- [x] Podemos instanciar um único Trem?
- [x] Podemos _setar_ o _time_ de Empacotamento de cada Empacotador?
- [x] Podemos _setar_ o _time_ de viagem do Trem?
- [x] Garantimos que tanto o Empacotador quanto o Trem são CPU-Bound?

**Comment by gabriel-vieira06** [comment]
Referenciando task: _Trem NÃO pode ser instanciado múltiplas vezes?_

**Na implementação atual, o Trem ainda pode ser instanciado mais de uma vez.**
Espera-se que a GUI limite a capacidade do usuário de fazê-lo a fim de evitar bugs.

**Comment by gabriel-vieira06** [comment]
Tasks concluídas, issue fechada.
